name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.10'

      - name: Install dependencies with uv
        run: |
          uv pip install --system -e .[dev]

      - name: Lint with ruff
        run: |
          ruff --version
          ruff check .

      - name: Type check with pyright
        run: |
          pyright --version
          pyright
