name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.10'

      - name: Install dependencies with uv
        run: |
          # Install only dev tooling and do not install the project itself
          uv sync --only-dev --no-install-project

      - name: Run pre-commit (all files)
        run: |
          uv run --no-project pre-commit --version
          uv run --no-project pre-commit run --all-files --show-diff-on-failure
